version: "3.9"
services:
  chanchito:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - monguito
    volumes:
      - .:/home/app
  monguito:
    image: mongo 
    port:
      - "27017:27017"
    environment:
      mongo_initdb_root=nico
      mongo_initdb_root_password=0000
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data: